### ISSUE TITLE
OBS Plugin?

### ISSUE THREAD

**Issue by HiroiSekai** [sayonari/twitchTransFreeNext#32]
Hello, thank you for making this amazing translator! It's a small feature request to remove another open app on my desktop, but is it possible in the future to make this a simple OBS Studio plugin? You could just add it as a source with the settings changeable in the app panel. I think it would simplify the app for a lot of people; I know and appreciate tons of people on Twitch are using this translator right now.

Thank you again!

**Comment by didotb** [comment]
That would require re-coding all of this in C language, OR making a separate OBS Plugin written in C that would communicate with this app. But then that second option would mean you'd need to have the app downloaded in your PC, and the plugin would simply run this python app in the background (Which means it's still running in your PC).

Judging from all the dependencies required, only a few of them have support for C (having a C API officially made), so the first option would be harder to do, not to mention would take a long time.

OBS does indeed accept python plugins, but most of the useful functions (for this app) are not accessible unless you switch to the C API. Source: [Python/Lua Scripting](https://obsproject.com/docs/scripting.html)

So I suggest another option which is [Replit](https://replit.com/). You can make a repo, do `git clone` to this git repo, install dependencies, and run the app there. But that would mean keeping the tab open to make sure the app doesn't stop since it automatically stops every 5 minutes unless you pay for the pro account (there is a trick to this, by creating a web page, and using 3rd party apps to ping your website every 5 minutes)

**Comment by HiroiSekai** [comment]
Repl.it is a great idea I hadn't considered, thanks! I know some basics of coding within Repl.it so I can even hook it up to my UptimeRobot server to keep it up.

I'll close the request.
