### ISSUE TITLE
The program is just echo'ing whatever I type in. 

### ISSUE THREAD

**Issue by PreachingSkateboarder** [sayonari/twitchTransFreeNext#71]
If I write "hello" in chat the TTS says "hello". If I write something in Japanese it echo's back to me what I wrote in Japanese. I am wanting this to be inverse so that when someone types something in Japanese or English, it will echo the opposite back to me translated so that I can communicate properly with a Japanese audience. I've tried switching the lang_Trans and lang_Home. I've tried "readonlytheselang". I changed from deepl to google. I tried changing co.jp to com. And I ran debug during alot of it to see if I could catch the issue but I can't figure it out. 
![issues 1](https://github.com/user-attachments/assets/7f7990c2-7fdb-4921-9e81-b095d777717b)
![issues 2](https://github.com/user-attachments/assets/283d310c-09fe-48cf-a872-ea8da0339f90)
![issues 3](https://github.com/user-attachments/assets/0367dde5-1aab-48c1-bb73-69a2bd0c8ac5)

**Comment by didotb** [comment]
I see the `[Local Database] (SQLite database file)` in the debug output.
You might have to delete the local sqlite file before you start the app.

The local database is there to aid with translation whenever DeepL refuses to translate further due to daily limit, or Google Translate refusing to reply.
As it seems you're still in the testing phase, you might have to repeat this, it shouldn't mess up in the future once you're fully setup.

**Comment by PreachingSkateboarder** [comment]
That worked for me. Thank you very much. I am trying to go through the steps now for the live translations tool as well. <3

**Comment by didotb** [comment]
> That worked for me.

If you don't have any other question regarding this topic, kindly close this issue, Sayonari might be too busy to check on every issue here, so they can't close it for us. Would also help other people looking at the closed issues on how it was solved.
